FROM python:3.12.0-slim

# Set up a new user named "user" with user ID 1000
RUN useradd -m -u 1000 user

# Switch to the "user" user
USER user

# Set home to the user's home directory
ENV HOME=/home/user \
    PATH=/home/user/.local/bin:$PATH

# Set the working directory to the user's home directory
WORKDIR $HOME/app

# Copy requirements.txt
COPY requirements.txt .

# Install python dependencies
RUN pip install -r requirements.txt

# Copy source code
COPY --chown=user src/ .

# Copy example configuration
COPY --chown=user examples/server_configs/risk_assessment.yaml risk_assessment.yaml

# Set PythonPath to source directory
ENV PYTHONPATH="$PYTHONPATH:$HOME/app"